name: Curl to Google on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  curl-google:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Curl Google
        run: |
          echo "Triggering a curl request to Google..."
          curl -I https://www.google.com
